<?php
class MyArray extends ArrayObject
{
private $A = "asda";
public $B = 15;
private $data = [];

    /**
     * MyArray constructor.
     * @param array $data
     */
    public function __construct(array $data)
    {
        $this->data = $data;
    }

    /**
     * @return array
     */
    public function getData(): array
    {
        return $this->data;
    }

    /**
     * @param array $data
     */
    public function setData(array $data): void
    {
        $this->data = $data;
    }

    public function append($value)
    {
//        parent::append($value); // TODO: Change the autogenerated stub
        $this->data[] = $value;
    }

    public function __toArray()
    {
        $s = [];
        foreach ($this->data as $key => $item) {
            $s[$key] = $item;
        }
        return $s;
    }


}